import {StyleSheet} from 'react-native';


export const Global_Styles = StyleSheet.create({
home_container: {
    marginTop:60,
    flex: 1,
    alignItems: 'center',
},
each_table:{
    width:'90%', 
    marginTop:10,
    justifyContent:'flex-start'
},
text_each_table: {
    fontWeight:'600',
    fontSize:24,
},
names_each_table:{
    paddingRight:50,
    height:80,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#fff', 
    borderRadius:20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#AAAAAA',
},
stats_table:{
    justifyContent:'center',
    paddingVertical:20,
    alignItems:'center',
    backgroundColor:'#fff', 
    borderRadius:20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#AAAAAA',
},
home_options:{
    borderBottomRightRadius:18,
    borderTopRightRadius:18,
    borderWidth:3,
    borderTopWidth:0,
    borderColor:'#AAAAAA',
    backgroundColor:'#E9E9E9', 
    width:80, 
    height:"100%",
    position:'absolute', 
    right:0,
    alignItems:'center',
    justifyContent:'center',
},
home_addbutton:{
    borderRadius: 14,
    backgroundColor:'#E9E9E9', 
    height:80, 
    width:'90%',
    borderBottomWidth:3,
    borderRightWidth:3,
    borderColor:"#AAAAAA",
    alignItems: 'center',
    justifyContent:'center',
    marginVertical:20,
},
home_plus1:{
    position:'absolute',
    borderRadius:10,
    width:6,
    height:40,
    backgroundColor:'black'
},
home_plus2:{
    position:'absolute',
    borderRadius:10,
    width:40,
    height:6,
    backgroundColor:'black'
},
add_plus1:{
    alignItems: 'center',
    justifyContent: 'center',
    position:'absolute',
    borderRadius:10,
    width:4,
    height:30,
    backgroundColor:'black'
  },
add_plus2:{
    position:'absolute',
    borderRadius:10,
    width:30,
    height:4,
    backgroundColor:'black'
},
add_modal:{
    width:'100%', 
    marginTop:-50, 
    marginBottom:-50, 
    alignSelf:'center',
    alignItems:'center', 
    justifyContent:'center', 
    backgroundColor:'rgba(26,32,46,0.3)',
},
modalView: {
    margin: 20,
    backgroundColor: "#F1F1F1",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    elevation: 5
},
writebar: {
    marginTop:20,
    alignItems: 'center',
    justifyContent: 'center',
    width:300,
    height:80,
    backgroundColor:'#ffff', 
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    paddingHorizontal:10,
    borderColor:'#E6E6E6',
},
writename:{
    padding:20,
    fontSize:24,
    textAlign:'center',
    fontWeight:'400',
},
small_writename:{
    fontSize:18,
    width:80,
    fontWeight:'300'
},
vertical_line:{
    height:'100%',
    width:3,
    backgroundColor:'#000000',
    borderRadius:20, 
    marginLeft:10
},
modal_cancel:{
    marginRight:7,
    alignItems: 'center',
    justifyContent: 'center',
    width:140,
    height:70,
    backgroundColor: "#F1AEAF",
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#DEA2A3',
},
modal_save:{
    marginLeft:7,
    alignItems: 'center',
    justifyContent: 'center',
    width:140,
    height:70,
    backgroundColor: "#ADF6AC",
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#9EE79E',
},
add_main_text:{
    fontWeight:'500',
    fontSize:24,
    textAlign:'center'
},
add_bigbar:{
    marginTop:20,
    alignItems: 'center',
    justifyContent: 'center',
    width:300,
    backgroundColor:'#ffff', 
    borderRadius: 20,
    paddingVertical: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#AAAAAA',
},
miniline:{
    height:4,
    borderRadius:20,
    marginVertical:15,
    width:250,
    backgroundColor:'#C9C9C9'
},
add_delete_element:{
    alignSelf:'flex-start',
    borderBottomRightRadius:20,
    borderTopRightRadius:20,
    borderWidth:3,
    borderColor:'#DEA2A3',
    backgroundColor:'#F1AEAF', 
    width:50, 
    height:'103%', 
    position:'absolute', 
    right:-3,
    alignItems:"center",
    justifyContent:"center", 
},
each_title:{
    width:'90%',
    paddingRight:60,
    minHeight:56,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#ffff', 
    marginVertical:4,
    borderRadius:20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#aaaaaa',
},
add_each_task:{
    width:'90%',
    minHeight:80,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#F4F4F4', 
    marginVertical:4,
    borderRadius:20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#E6E6E6',
    flexDirection:'row'
},
add_cancel:{
    marginVertical:20,
    marginHorizontal:10,
    alignItems: 'center',
    justifyContent: 'center',
    width:'40%',
    height:80,
    backgroundColor: "#F1AEAF",
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#DEA2A3',
},
add_delete_table:{
    marginHorizontal:10,
    alignItems: 'center',
    justifyContent: 'center',
    height:80,
    backgroundColor: "#F1AEAF",
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#DEA2A3',
    width:'85%', 
    marginTop:20, 
},
add_save:{
    marginVertical:20,
    marginHorizontal:10,
    alignItems: 'center',
    justifyContent: 'center',
    width:'40%',
    height:80,
    backgroundColor: "#ADF6AC",
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#9EE79E',
},
add_add_new_element:{
    marginTop:10,
    alignItems: 'center',
    justifyContent: 'center',
    width:260,
    height:80,
    backgroundColor: "#ADF6AC",
    borderRadius: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#9EE79E',
},
main_bigbar:{
    marginBottom:20,
    alignItems: 'center',
    width:"80%",
    backgroundColor:'white', 
    borderRadius: 20,
    paddingTop: 20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#AAAAAA',
  },   
main_name:{
    width:'100%',
    height:100,
    justifyContent:'center',
    alignItems:'flex-end',
    paddingBottom:14, 
    flexDirection:'row',
    backgroundColor:'#fff', 
    borderBottomRightRadius:40,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#E6E6E6',
},  
main_arrow:{
    position:'absolute', 
    alignItems:'center', 
    justifyContent:'center', 
    left:0,
    width:70, 
    height:70
},
main_miniline:{
    height:4,
    borderRadius:20,
    marginTop:10,
    marginBottom:12,
    width:'90%',
    backgroundColor:'#c9c9c9'
},
main_minus:{
    flex:1,
    alignItems: 'center',
    justifyContent: 'center',
    width:'50%',
    height:40,
    backgroundColor: "#F1AEAF",
    borderBottomLeftRadius: 20,
    borderLeftWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#DEA2A3',
},
main_plus:{
    flex:1,
    alignItems: 'center',
    justifyContent: 'center',
    width:'50%',
    height:40,
    backgroundColor: "#ADF6AC",
    borderBottomRightRadius: 18,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#9EE79E',
  },
main_plus1:{
    alignItems: 'center',
    justifyContent: 'center',
    position:'absolute',
    borderRadius:10,
    width:4,
    height:20,
    backgroundColor:'black'
},
main_plus2:{
    position:'absolute',
    borderRadius:10,
    width:20,
    height:4,
    backgroundColor:'black'
},
maint_delete_items:{
    width:'29%', 
    margin:5, 
    height:40,
    backgroundColor:'#fff', 
    alignItems:'center', 
    justifyContent:'center',
    borderRadius:20,
},
options_styles:{
    width:'29%', 
    margin:5, 
    height:80,
    backgroundColor:'#fff', 
    alignItems:'center', 
    justifyContent:'center',
    borderRadius:20,
},
main_top_buttons:{
    padding:10,
    flex:1,
    alignSelf:'center',
    justifyContent:'center',
    alignItems:'center',
    minHeight:60,
    marginHorizontal:'3%',
    backgroundColor:'#ffff',
    borderRadius:20,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor:'#AAAAAA',
},
main_top_text:{
    fontSize:20,
    textAlign:'center',
    fontWeight:'500'
}
});